# Generated by Django 5.0.6 on 2024-06-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('natural_habitat', models.CharField(max_length=255)),
                ('life_expectancy', models.CharField(max_length=255)),
                ('state_of_conservation', models.CharField(max_length=255)),
                ('interacciones_con_humanos', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_store.species')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
