# Generated by Django 5.0.6 on 2024-06-22 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_store', '0002_animals_delete_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animals',
            name='interacciones_con_humanos',
        ),
        migrations.RemoveField(
            model_name='animals',
            name='state_of_conservation',
        ),
    ]
